### ISSUE TITLE
Handle # Color Prefix Case

### ISSUE THREAD

**Issue by pkluz** [Originate/OriginateTheme#11]
@rweindl @allewun Right now OriginateTheme's [hex color parser](https://github.com/Originate/OriginateTheme/blob/master/OriginateTheme/Sources/Categories/UIColor%2BOTHex.m#L17) fails to parse colors that are prefixed by a `#` character.

This should be handled gracefully.

**Comment by rweindl** [comment]
I gonna take care of that.
