### ISSUE TITLE
Boolean Data Types

### ISSUE THREAD

**Issue by pkluz** [Originate/OriginateTheme#12]
@rweindl @allewun 

The components fields require additional fields that can handle boolean values.

E.g. given:
```
"components" : {
        "tabBar" : {
            "colors" : {
                "background" : "FFFFFF",
                "tint" : "4A4A4A"
            },
            "isTranslucent": true
        },
...
}
```

should generate:

```@property (nonatomic, assign, readonly) BOOL navBarIsTranslucent;```

**Comment by chhaylatte** [comment]
Just to make sure, do we want the public property to also be readwrite?

**Comment by pkluz** [comment]
yikes no we do not :) Sorry about that!
