### ISSUE TITLE
Font Initialization Bug

### ISSUE THREAD

**Issue by pkluz** [Originate/OriginateTheme#36]
When a theme is instantiated without an underlying definition (`Theme()`), and subsequently proceeds to evaluating the following function:

```swift
extension UIFont {
    class func font(_ keyPath: String, dictionary: [String: Any], fallback: UIFont) -> UIFont {
        let size = Float(dictionary[keyPath: KeyPath("\(keyPath).size")] as? String ?? "0.0") ?? Float(UIFont.systemFontSize)
        let name = dictionary[keyPath: KeyPath(keyPath)] as? String ?? fallback.fontName
        
        return UIFont(name: name, size: CGFloat(size)) ?? fallback
    }
}
```

the fallback is _NOT_ returned correctly. Instead, the correct font name with size 0 is returned, which makes the return statement never produce `nil`. Instead it returns `Helvetica` at size `0.0`, which is not the desired behavior.

**Comment by allewun** [comment]
https://github.com/Originate/OriginateTheme/commit/639cb09869dfc924665ff642659390727a518f2c

**Comment by pkluz** [comment]
would you look at that.
